import { redirect } from "next/navigation";
import { Container } from "@mantine/core";
import type { Metadata } from "next";
// Utils
import { createClient } from "@/utils/supabase/server";

export const metadata: Metadata = {
  title: "Login Layout",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (user) redirect("/");
  return <Container fluid>{children}</Container>;
}
