import { Container } from "@mantine/core";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login Layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Container fluid>{children}</Container>;
}
